# Generated by Django 4.1.5 on 2023-01-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_credential', to='websites.website'),
        ),
    ]
