# Generated by Django 4.1.5 on 2023-01-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_website_user'),
        ('credentials', '0003_alter_credential_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='websites.website'),
        ),
    ]
