# Generated by Django 4.1.5 on 2023-01-22 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_passwords', to='websites.website'),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
